import streamlit as st
import time
st.title("student")
st.write("name is varsha")
st.write(1123)
st.write([1,2,3,4,5])
st.header("varsha")
st.subheader("age")
st.text_input("enter some text")
st.number_input("enter a number",step=1)
st.markdown("# heading1")
st.markdown("## heading2")
st.markdown("### heading3")
st.markdown("**worldcup**")
st.markdown("*italic*")
st.checkbox("i agree terms and conditions")
st.text_area("enter a longer text")
st.radio("choose an option",["option 1","option 2","option 3"])
num=st.selectbox("Select an option",["option A","option b","option c"])
st.write(f"You selected: {num}")
st.sidebar.write("tis is sidebar")
st.sidebar.selectbox("menu",["A","B","c"])
with st.form("my_form"):
    st.write("inside the form")
    name=st.text_input("Name")
    age=st.number_input("Age",step=1)
    password = st.text_input("Password",type="password")
    text=st.text_area("addition info address")
    submitted=st.form_submit_button("Submit")
    if submitted:
        st.write(f"Name: {name},Age: {age}")
st.date_input("select a date")
st.time_input("select a time")
st.color_picker(("select a color"))
st.latex('''E=mc^2''')
col1,col2=st.columns(2)
with col1:
    st.text_input("enter a first name")
with col2:
    st.text_input("enter a last name")
#st.title("Feedbact function ex")
st.slider("select a value",0,100)
progess=st.progress(50)
st.markdown("---")
with st.spinner("waiting..."):
    time.sleep(1)
    st.write("process completed")
st.balloons()
st.snow()

